# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1327106280);
user_pref("app.update.lastUpdateTime.background-update-timer", 1327106280);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1327106280);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1327106280);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 1048576);
user_pref("browser.migration.version", 5);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage_override.buildID", "20111220165912");
user_pref("browser.startup.homepage_override.mstone", "rv:9.0.1");
user_pref("browser.taskbar.lastgroupid", "Mozilla.Firefox.9.0.1");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 6);
user_pref("extensions.enabledAddons", "firebug@software.joehewitt.com:1.9.0,{972ce4c6-7e08-4474-a285-3208198ce6fd}:9.0.1");
user_pref("extensions.firebug.addonBarOpened", true);
user_pref("extensions.firebug.currentVersion", "1.9.0");
user_pref("extensions.firebug.toolbarCustomizationDone", true);
user_pref("extensions.installCache", "[{\"name\":\"winreg-app-global\",\"addons\":{\"{20a82645-c095-46ed-80e3-08825760534b}\":{\"descriptor\":\"C:\\\\Windows\\\\Microsoft.NET\\\\Framework\\\\v3.5\\\\Windows Presentation Foundation\\\\DotNetAssistantExtension\",\"mtime\":1258987119295}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files\\\\Mozilla Firefox\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1325963377724},\"{AB2CE124-6272-4b12-94A9-7303C7397BD1}\":{\"descriptor\":\"C:\\\\Program Files\\\\Mozilla Firefox\\\\extensions\\\\{AB2CE124-6272-4b12-94A9-7303C7397BD1}\",\"mtime\":1283945442454}}},{\"name\":\"winreg-app-user\",\"addons\":{\"moveplayer@movenetworks.com\":{\"descriptor\":\"C:\\\\Users\\\\Adam\\\\AppData\\\\Roaming\\\\Move Networks\",\"mtime\":1264359725937}}},{\"name\":\"app-profile\",\"addons\":{\"firebug@software.joehewitt.com\":{\"descriptor\":\"C:\\\\workspace\\\\orcaproject\\\\src\\\\test\\\\resources\\\\FirefoxProfile\\\\extensions\\\\firebug@software.joehewitt.com.xpi\",\"mtime\":1327106160205}}}]");
user_pref("extensions.lastAppVersion", "9.0.1");
user_pref("extensions.lastPlatformVersion", "9.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.lastCategory", "addons://search/firebug");
user_pref("extensions.ui.locale.hidden", true);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 79506);
user_pref("places.history.expiration.transient_optimal_database_size", 127208652);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("toolkit.telemetry.prompted", 2);
user_pref("toolkit.telemetry.rejected", true);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1329698143);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
